version: "3"
services:
  spooky_nervape_website:
    container_name: spooky_nervape_website
    image: "node:16"
    restart: always
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/home/node/app
    ports:
      - "3005:3005"
    command: /bin/bash -c "yarn && yarn run build && yarn run preview"
