version: "3"
services:
  nervape_website:
    container_name: nervape_website
    image: "node:16"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/home/node/app
    ports:
      - "3000:3000"
    command: /bin/bash -c "yarn && yarn run build && yarn run preview"
